version: "3.8"

services:
  db:
    image: postgres:16
    container_name: avito-merch-db
    restart: always
    environment:
      POSTGRES_USER: champ001
      POSTGRES_PASSWORD: 123champ123
      POSTGRES_DB: merge-store
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: avito-merch-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: champ001
      DB_PASSWORD: 123champ123
      DB_NAME: merge-store
      JWT_SECRET_KEY: "zN1qT3v5PbC+fKmB9pVjQ13O8+wsyxMGj5L9C/wT4lU="
    command: ["/app/merch-store"]

volumes:
  db-data:
