version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_merch
    restart: always
    environment:
      DB_HOST: "db"
      POSTGRES_DB: merge-store
      POSTGRES_USER: champ001
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "champ001", "-d", "merge-store"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: merch_store
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8080:8080"
    command: ["/app/entrypoint.sh"]

volumes:
  postgres_data:
