version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: merch_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONFIG_PATH: "/configs/config.yaml"
      ENV_PATH: "/configs/.env"
    ports:
      - "8080:8080"
    entrypoint: >
      sh -c "goose -dir ./migrations postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable up && ./app"

volumes:
  postgres_data:
