global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'merch_app'
    static_configs:
      - targets: ['merch_store_app:9090']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
