basePath: /api
host: localhost:8080
info:
  contact:
    email: epchamp001@gmail.com
    name: Egor Ponyaev
    url: https://github.com/epchamp001
  description: This is a service that will allow employees to exchange coins and purchase
    merch with them.
  license:
    name: MIT
  title: Merch Store
  version: "1.0"
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
