// Code generated by mockery v2.53.0. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "avito-tech-merch/internal/models"
)

// MerchRepository is an autogenerated mock type for the MerchRepository type
type MerchRepository struct {
	mock.Mock
}

// GetAllMerch provides a mock function with given fields: ctx
func (_m *MerchRepository) GetAllMerch(ctx context.Context) ([]*models.Merch, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllMerch")
	}

	var r0 []*models.Merch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Merch, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Merch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Merch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchByID provides a mock function with given fields: ctx, id
func (_m *MerchRepository) GetMerchByID(ctx context.Context, id int) (*models.Merch, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchByID")
	}

	var r0 *models.Merch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*models.Merch, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *models.Merch); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMerchByName provides a mock function with given fields: ctx, merchName
func (_m *MerchRepository) GetMerchByName(ctx context.Context, merchName string) (*models.Merch, error) {
	ret := _m.Called(ctx, merchName)

	if len(ret) == 0 {
		panic("no return value specified for GetMerchByName")
	}

	var r0 *models.Merch
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Merch, error)); ok {
		return rf(ctx, merchName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Merch); ok {
		r0 = rf(ctx, merchName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Merch)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, merchName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMerchRepository creates a new instance of MerchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMerchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MerchRepository {
	mock := &MerchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
