env: "dev"

application:
  app: "merge-store"

public_server:
  enable: true
  endpoint: "localhost"
  port: 8080

storage:
  hosts:
    - "localhost"
  port: 5432
  database: "merge-store"
  username: "champ001"
  ssl_mode: "disable"
  connection_attempts: 3

jwt:
  secret_key: ""
  token_expiry: 3600